"""
    Parameters used by the ETL
"""

# IMPROVEMENTS
#  Replace this file by using parameters stored in a secrets management solution like AWS Secrets Manager or
#  AWS Parameter Store that will be accessed by the ETL at run time

event_store:
    web_host: 167.99.81.240
    web_port: 2113
    tcp_host: 167.99.81.240
    tcp_port: 1113
    username: readonly
    password: xxxxxxx

companies_house:
  url: 'http://download.companieshouse.gov.uk/'
